% plot camera FoV
function plotCamFoV(rob, R0c, P0c, tag, ax)

[vfov, ffof]=getCamFoV(rob, R0c, P0c);

alpha = 0.2; 
% upper FoV
patch('faces',ffof{1},...
      'vertices',vfov,...
      'facecolor','b',...
      'edgecolor','k',...
      'facealpha',alpha,...
      'parent',ax,...
      'tag',tag);
  
alpha = 0.5; 
% truncated FoV
patch('faces',ffof{2},...
      'vertices',vfov,...
      'facecolor','r',...
      'edgecolor','none',...
      'facealpha',alpha,...
      'parent',ax,...
      'tag',tag);
  
alpha = 0.2; 
% cap FoV
patch('faces',ffof{3},...
      'vertices',vfov,...
      'facecolor','c',...
      'edgecolor','none',...
      'facealpha',alpha,...
      'parent',ax,...
      'tag',tag);
  
  