% plot camera FoV with semplied cone
function plotCamFoVCone(rob, N0c, P0c, tag, ax)


[fmin, fmax, alfa]=getCamFoVCone(rob);

alpha = 0.2; 
% upper FoV
[X, Y, Z]=createConeObj(0, fmin, alfa, P0c, N0c);
surf(X, Y, Z,...
      'facecolor','b',...
      'edgecolor','none',...
      'facealpha',alpha,...
      'parent',ax,...
      'tag',tag);
  
alpha = 0.5; 
% truncated FoV
[X, Y, Z]=createConeObj(fmin, fmax, alfa, P0c, N0c);
surf(X, Y, Z,...
      'facecolor','r',...
      'edgecolor','none',...
      'facealpha',alpha,...
      'parent',ax,...
      'tag',tag);
    
  